### ISSUE TITLE
Work only plugged in computer

### ISSUE THREAD

**Issue by th1460** [m5stack/TimerCam-arduino#4]
Hello! How the camera work unplugged from computer? I am using the web_cam example. Thanks

**Comment by padbol2000** [comment]
set your ssid and password according to your wifi network

**Comment by th1460** [comment]
> set your ssid and password according to your wifi network

I set, but when is unplugged I lose the connection. This in `web_cam` code example. The led blue light in this example is turn off, too. Do I have to change the script in `web_cam` example to work properly (with autonomy from computer)?

**Comment by nicolas-f** [comment]
You have to call bat_init() in the setup function in order to keep battery on when unpugged

**Comment by th1460** [comment]
Thanks this work for me!
