### ISSUE TITLE
 bmm8563.c Date Error

### ISSUE THREAD

**Issue by jdr-sensen** [m5stack/TimerCam-arduino#7]
In bmm8563_getTime, the filter for the month register seems to be incorrect, it is currently:
data->month = BCD2Byte(time_buf[5] & 0x0f);

However, this causes months larger than 9 to have some of the data lost, e.g. 10->0, 11->1, 12->2

I believe the intended filter is:
data->month = BCD2Byte(time_buf[5] & 0x1f);

**Comment by TinyuZhao** [comment]
Thank you for your help!
