### ISSUE TITLE
how can I view the source code for the firmwares provided on M5Burner?

### ISSUE THREAD

**Issue by jackchealdang** [m5stack/TimerCam-arduino#9]
I would like to get the token for the images taken using the firmware on M5Burner, but I'm unable to view the code for it

**Comment by TinyuZhao** [comment]
Sorry for the late reply. There is currently a button to get a token on Burner.
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/44396641/183795440-dda848f9-2818-4c42-ae46-6ea51fec8eb1.png">
